{
 "title": "Rutorret-Rtorrent Truenas scale",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (kube_deployment_status_replicas{exported_namespace=\"ix-rtorrent-rutorrent\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Currently Downloading",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum by(namespace) (rtorrent_torrents_total{view=\"main\"})) - on () (sum by(namespace) (rtorrent_torrents_total{view=\"seeding\"}))) - on () (sum by(namespace) (rtorrent_torrents_total{view=\"stopped\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Stopped Torrents",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rtorrent_torrents_total{view=\"stopped\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Seeding Torrents",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rtorrent_torrents_total{view=\"seeding\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Torrents",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace) (rtorrent_torrents_total{view=\"main\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Current Download Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace) (irate(rtorrent_downloaded_bytes[29s]) / (1024 * 1024)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(namespace) (irate(rtorrent_uploaded_bytes[20s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Max Speed Per Day", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Todays Max Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (namespace) (irate(rtorrent_downloaded_bytes[20s]) / 1048576)[1d:])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max  Upload Speed For the Day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (namespace) (irate(rtorrent_uploaded_bytes[20s]))[1d:])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Total Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Downloaded in GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(increase(rtorrent_downloaded_bytes[2y]) / (1024 * 1024 * 1024))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Uploads in GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(increase(rtorrent_uploaded_bytes[10y]) / (1024 * 1024 * 1024))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Old optional Fields ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Torrent Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 8, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((rtorrent_torrents_total{view=\"main\"} - on () rtorrent_torrents_total{view=\"seeding\"}) - on () rtorrent_torrents_total{view=\"stopped\"})",
       "legendFormat": "Downloading"
      },
      {
       "expr": "(sum by(namespace) (rtorrent_torrents_total{view=\"stopped\"}))",
       "legendFormat": "Stopped"
      },
      {
       "expr": "(sum by(namespace) (rtorrent_torrents_total{view=\"seeding\"}))",
       "legendFormat": "Seeding"
      },
      {
       "expr": "(sum by(namespace) (rtorrent_torrents_total{view=\"main\"}))",
       "legendFormat": "All Torrents"
      }
     ]
    }
   ]
  }
 ]
}